---
services:
  elasticsearch1:
    image: "elasticsearch:8.15.1"
    container_name: elasticsearch1
    hostname: elasticsearch1
    environment:
      - "node.name=elasticsearch1"
      - "cluster.name=es-cluster"
      - "bootstrap.memory_lock=true"
      - "discovery.seed_hosts=elasticsearch2,elasticsearch3"
      - "cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3"
      - "ES_JAVA_OPTS=-Xmx1024m -Xms1024m"
      - "xpack.security.enabled=false"
      - "xpack.ml.enabled=false"
      - "xpack.graph.enabled=false"
      - "xpack.watcher.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: bridge
    ports:
      - "9200:9200"
    volumes:
      - "/mnt/main/service/elasticsearch1/:/usr/share/elasticsearch/data/"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
  elasticsearch2:
    image: "elasticsearch:8.15.1"
    container_name: elasticsearch2
    hostname: elasticsearch2
    environment:
      - "node.name=elasticsearch2"
      - "cluster.name=es-cluster"
      - "bootstrap.memory_lock=true"
      - "discovery.seed_hosts=elasticsearch1,elasticsearch3"
      - "cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3"
      - "ES_JAVA_OPTS=-Xmx1024m -Xms1024m"
      - "xpack.security.enabled=false"
      - "xpack.ml.enabled=false"
      - "xpack.graph.enabled=false"
      - "xpack.watcher.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: bridge
    ports:
      - "9201:9200"
    volumes:
      - "/mnt/main/service/elasticsearch2/:/usr/share/elasticsearch/data/"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
  elasticsearch3:
    image: "elasticsearch:8.15.1"
    container_name: elasticsearch3
    hostname: elasticsearch3
    environment:
      - "node.name=elasticsearch3"
      - "cluster.name=es-cluster"
      - "bootstrap.memory_lock=true"
      - "discovery.seed_hosts=elasticsearch1,elasticsearch2"
      - "cluster.initial_master_nodes=elasticsearch1,elasticsearch2,elasticsearch3"
      - "ES_JAVA_OPTS=-Xmx1024m -Xms1024m"
      - "xpack.security.enabled=false"
      - "xpack.ml.enabled=false"
      - "xpack.graph.enabled=false"
      - "xpack.watcher.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    network_mode: bridge
    ports:
      - "9202:9200"
    volumes:
      - "/mnt/main/service/elasticsearch3/:/usr/share/elasticsearch/data/"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
