{
 "title": "NetFlow",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "source_ip",
    "label": "Source IP",
    "query": "{\"find\": \"terms\", \"field\":\"netflow.post_nat_source_ipv4_address\"}"
   },
   {
    "name": "dest_ip",
    "label": "Destination IP",
    "query": "{\"find\": \"terms\", \"field\": \"netflow.post_nat_destination_ipv4_address\"}"
   },
   {
    "name": "direction",
    "label": "Direction",
    "query": "{\"find\": \"terms\", \"field\": \"network.direction\"}"
   },
   {
    "name": "protocol",
    "label": "protocol",
    "query": "{\"find\": \"terms\", \"field\": \"network.transport\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Consuming traffic  by localnet",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "netflow.post_nat_destination_ipv4_address",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "4", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "4", "type": "sum" }
     ],
     "query": "network.direction: inbound",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Address External",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.ip",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "4", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "4", "type": "sum" }
     ],
     "query": "network.direction: inbound",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Protocols $direction Usage",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "network.transport",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "network.direction: $direction",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Country $direction",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.geo.country_name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Russia Provider $direction",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.as.organization.name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "type": "sum" }
     ],
     "query": "source.geo.country_iso_code: RU",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Traffic Speed $direction",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "source.ip",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "field": "netflow.post_nat_destination_ipv4_address",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      },
      {
       "field": "network.transport",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "1" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "settings": { "script": "_value*8/60" }, "type": "sum" }
     ],
     "query": "network.direction: $direction AND netflow.post_nat_source_ipv4_address: $source_ip AND netflow.post_nat_destination_ipv4_address: $dest_ip AND network.transport: $protocol",
     "timeField": "@timestamp"
    },
    {
     "alias": "Total $direction",
     "bucketAggs": [
      {
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "network.bytes", "id": "1", "settings": { "mode": "sum", "script": "_value*8", "unit": "second" }, "type": "rate" }
     ],
     "query": "network.direction: $direction",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Traffic Statistic",
   "type": "table",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "netflow.post_nat_source_ipv4_address",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "netflow.post_nat_destination_ipv4_address",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "network.direction",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "network.transport",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "network.bytes",
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}